accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout")
]

articles/urls.py
from django.urls import path

from . import views

app_name = "articles"

urlpatterns = [
    path("", views.article_list, name="list"),
    path("create/", views.article_create, name="create"),
    path("<slug:slug>", views.article_detail, name="detail"),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("articles/", include("articles.urls")),
    path("about/", views.about),
    path("", views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True)
    # add in author later

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ["title", "body", "slug", "thumb"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log user in
            login(request, user)

            return redirect("articles:list")
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html", {"form": form})


def login_view(request):
    print("login")
    print(request.method)
    if request.method == "POST":
        print("if request.method")
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            print("form.is_valid")
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                print("if login view")
                return redirect(request.POST.get("next"))
            else:
                print("else login view")
            return redirect("articles:list")

    else:
        print("else request.method")

        form = AuthenticationForm()

    return render(
        request,
        "accounts/login.html",
        {
            "form": form,
        },
    )


def logout_view(request):
    if request.method == "POST":
        logout(request)
        print('log out view')
        return redirect("articles:list")

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

# from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html", {"articles": articles})


def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, "articles/article_detail.html", {"article": article})


# @login_required(login_url="/accounts/login/")
def article_create(request):
    form = forms.CreateArticle()
    return render(request, "articles/article_create.html"), {"form": form}

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    # return HttpResponse("HOMEPAGE")
    return render(request, "homepage.html")


def about(request):
    # return HttpResponse("ABOUT")
    return render(request, "about.html")

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %} {% block content%}

<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %} {{form}} {% if request.GET.next %}
  <input type="hidden" name="next" value="{{request.GET.next}}" />
  {% endif %}
  <input type="submit" value="Login" />
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %} {% block content%}

<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token %} {{form}}
  <input type="submit" value="Signup" />
</form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %} {% block content%}

<div class="create-article">
  <h2>CREATE A NEW ARTICLE</h2>
  <form class="site-form" action="index.html" method="POST">{{form}}</form>
</div>

{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %} {% block content%}

<div class="article-detail">
  <div class="article">
    <img src = "{{article.thumb.url}}">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %} {%block content%}
<h1>Article List</h1>
<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2><a href="{% url 'articles:detail' slug=article.slug%}">{{article.title}}</a></h2>
    <p>{{article.snippet}}</p>
    <p>{{article.date}}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}e

templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>About</title>
  </head>
  <body>
    <h1>About us</h1>
    <p>We love Django</p>
  </body>
</html>

templates/base_layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>BLOG</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}"
  </head>
  <body>
    <div class="wrapper">
      <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png'%}"/></a></h1>
      <nav>
        <ul>
          <li>
            <form class="logout-link" action="{% url 'accounts:logout'%}" method="post">
              {% csrf_token %}
              <button type="submit">Logout</button>
          </li>
        </ul>
      </nav>
      {% block content %} {% endblock%}
    </div>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the homepage</h1>
    <p>Welcome to Djangonautics</p>
  </body>
</html>